### ISSUE TITLE
Change window title.

### ISSUE THREAD

**Issue by xGodThunder** [asadadams/simple-electron-react-boilerplate#4]
Hey buddy,
I am using your boilerplate to build my project and I am not able to figure out how to change the title of minWindow.
Any suggestions would be appreciated.
Thanks and be safe.

**Comment by xGodThunder** [comment]
`mainWindow.on('page-title-updated', function(e) {
  e.preventDefault()
});`

this worked. thanks :)

**Comment by asadadams** [comment]
Alright , that is great @xGodThunder
