### ISSUE TITLE
electron build blank

### ISSUE THREAD

**Issue by xGodThunder** [asadadams/simple-electron-react-boilerplate#5]
Hey buddy,
When I build my pack, the app displays a blank page.
(see image for reference: https://pasteboard.co/J3pokGZ.png ).
I don't see any console errors, ut electron app won't able to find out index.html and other assets.

When I run dist/ files directly in the browser then it throws "require is not a function" error.

I am using `npm run package` for the build.

Any suggestion would be really appreciated :)

**Comment by xGodThunder** [comment]
https://github.com/xGodThunder/ultimate-downlaoder

check my repo if it is required.

**Comment by xGodThunder** [comment]
i made it working, it i because of this
`let dev = false;
if (process.defaultApp || /[\\/]electron-prebuilt[\\/]/.test(process.execPath) || /[\\/]electron[\\/]/.test(process.execPath)) {
  dev = true;
}`

Any suggestions about how to dev=false while packaging?

**Comment by asadadams** [comment]
First run `npm run dev` and in another console run `npm run start`

**Comment by xGodThunder** [comment]
I guess there is not start script.
it's complaining about it.

**Comment by asadadams** [comment]
There is a start command though. But in case that is not working run `electron .`

**Comment by asadadams** [comment]
@xGodThunder  I hope you have solved your issue so closing this issue
